

services:
  tictactoe-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_PATH=/app/data/tictactoe.db
    volumes:
      - ./data:/app/data
      # - ./public:/app/public:ro
    restart: unless-stopped
    # stop_grace_period: 30s
    # stop_signal: SIGTERM
    # command: ["npm", "start"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    user: "root"

  # Optional: Add a simple load balancer for testing
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - tictactoe-app
    restart: unless-stopped
    profiles:
      - load-balancer
