name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

# Set permissions for GitHub Container Registry
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/tictactoe-app

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: |
        # Check if package-lock.json is in sync with package.json
        if ! npm ci --dry-run; then
          echo "Package-lock.json is out of sync. Updating..."
          npm install
        else
          npm ci
        fi
    
    - name: Run tests
      run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy with Docker Compose
      run: |
        echo "Deploying with Docker Compose..."
        docker compose up -d
        
        # Wait for deployment
        sleep 30
        
        # Health check
        curl -f http://localhost:3000/health || exit 1
        
        echo "✅ Deployment successful!"
    
    - name: Run smoke tests
      run: |
        echo "Running smoke tests..."
        curl -f http://localhost:3000/health
        curl -f http://localhost:3000/
        echo "✅ Smoke tests passed!"

  load-test:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Wait for service to be ready
      run: |
        # Wait for Docker Compose to be ready
        sleep 10
        
        # Health check
        curl -f http://localhost:3000/health || exit 1
    
    - name: Run k6 load test
      uses: grafana/k6-action@v0.3.0
      with:
        filename: load-test.js
        flags: --out json=results.json
      env:
        TARGET_URL: http://localhost:3000
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: k6-results
        path: results.json
