name: Deploy TicTacToe Application

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
        - staging
        - production
        - development

# Set permissions for GitHub Container Registry and Security Scanning
permissions:
  contents: read
  packages: write
  security-events: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/tictactoe-app

jobs:
  # Test and Quality Assurance
  test:
    name: Test and Quality Check
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        # Use the npm retry script for robust dependency installation
        chmod +x scripts/npm-retry.sh
        ./scripts/npm-retry.sh install
    
    - name: Run linting
      run: |
        # Install eslint with retry logic
        ./scripts/npm-retry.sh retry npm install -g eslint
        eslint *.js public/*.js || echo "Linting completed"
    
    - name: Run tests
      run: npm test
    
    - name: Run security audit
      run: npm audit --audit-level=moderate || true
    
    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: coverage-${{ matrix.node-version }}
        path: coverage/
        retention-days: 30

  # Security scanning
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  # Build Docker image
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [test, security]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    outputs:
      image-tag: ${{ github.sha }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1
    
    - name: Set image tag output
      run: echo "image-tag=${{ github.sha }}" >> $GITHUB_OUTPUT

  # Deploy to Staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/develop' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging')
    environment: staging
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy with Docker Compose
      run: |
        echo "Deploying to staging environment..."
        docker compose -f docker-compose.staging.yml pull
        docker compose -f docker-compose.staging.yml up -d
    
    - name: Wait for deployment
      run: |
        sleep 30
        curl -f http://localhost:3000/health || exit 1
    
    - name: Run smoke tests
      run: |
        echo "Running smoke tests..."
        
        # Wait for application to be ready
        echo "Waiting for application to be ready..."
        for i in {1..30}; do
          if curl -s http://localhost:3000/health >/dev/null 2>&1; then
            echo "Application is ready!"
            break
          fi
          echo "Attempt $i/30: Application not ready yet..."
          sleep 2
        done
        
        # Test health endpoint
        echo "Testing health endpoint..."
        curl -f http://localhost:3000/health
        
        # Test main application
        echo "Testing main application..."
        curl -f http://localhost:3000/ -o /dev/null -w "HTTP Status: %{http_code}\n"
        
        echo "Smoke tests passed!"

  # Deploy to Production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production')
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy with Docker Compose
      run: |
        echo "Deploying to production with Docker Compose..."
        
        # Pull the latest image
        docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        
        # Deploy with Docker Compose
        docker compose -f docker-compose.yml up -d
        
        echo "✅ Production deployment completed successfully"
    
    - name: Run smoke tests
      run: |
        echo "Running production smoke tests..."
        
        # Wait for application to be ready
        echo "Waiting for application to be ready..."
        for i in {1..30}; do
          if curl -s http://localhost:3000/health >/dev/null 2>&1; then
            echo "Application is ready!"
            break
          fi
          echo "Attempt $i/30: Application not ready yet..."
          sleep 2
        done
        
        # Test health endpoint
        echo "Testing health endpoint..."
        curl -f http://localhost:3000/health
        
        # Test main application
        echo "Testing main application..."
        curl -f http://localhost:3000/ -o /dev/null -w "HTTP Status: %{http_code}\n"
        
        echo "✅ Production smoke tests passed!"
    
    - name: Run load test
      run: |
        echo "Running production load test..."
        
        # Install k6
        curl -L https://github.com/grafana/k6/releases/download/v0.47.0/k6-v0.47.0-linux-amd64.tar.gz | tar xz
        sudo cp k6-v0.47.0-linux-amd64/k6 /usr/local/bin/
        
        # Run load test
        k6 run load-test.js --out json=results.json
        
        echo "✅ Production load test completed!"
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: production-test-results-${{ github.run_number }}
        path: results.json

  # Load Testing
  load-test:
    name: Load Testing
    runs-on: ubuntu-latest
    needs: [deploy-staging, deploy-production]
    if: always() && (needs.deploy-staging.result == 'success' || needs.deploy-production.result == 'success')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run load test against deployed services
      run: |
        echo "Running load test against deployed services..."
        
        # Install k6
        curl -L https://github.com/grafana/k6/releases/download/v0.47.0/k6-v0.47.0-linux-amd64.tar.gz | tar xz
        sudo cp k6-v0.47.0-linux-amd64/k6 /usr/local/bin/
        
        # Set target URL (using localhost since we're testing the deployed service)
        TARGET_URL="http://localhost:3000"
        export TARGET_URL
        
        # Health check before load test
        echo "Performing health check on $TARGET_URL..."
        for i in {1..30}; do
          if curl -s "$TARGET_URL/health" >/dev/null 2>&1; then
            echo "Service is healthy and ready for load testing!"
            break
          fi
          echo "Attempt $i/30: Service not ready yet..."
          sleep 5
        done
        
        # Run load test
        k6 run load-test.js --out json=results.json
        
        echo "✅ Load test completed!"
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: k6-results-${{ github.run_number }}
        path: results.json
        retention-days: 90

  # Performance monitoring
  performance:
    name: Performance Monitoring
    runs-on: ubuntu-latest
    needs: load-test
    if: always() && needs.load-test.result == 'success'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download test results
      uses: actions/download-artifact@v4
      with:
        name: k6-results-${{ github.run_number }}
    
    - name: Analyze performance
      run: |
        echo "Analyzing performance results..."
        if [ -f results.json ]; then
          echo "Test results found"
          # Add performance analysis logic here
        else
          echo "No test results found"
        fi

  # Notifications
  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: [deploy-staging, deploy-production, load-test]
    if: always()
    
    steps:
    - name: Notify on success
      if: needs.deploy-production.result == 'success'
      run: |
        echo "✅ Production deployment successful!"
        # Add notification logic (Slack, email, etc.)
    
    - name: Notify on failure
      if: needs.deploy-production.result == 'failure'
      run: |
        echo "❌ Production deployment failed!"
        # Add notification logic (Slack, email, etc.)
    
    - name: Create deployment summary
      run: |
        echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Build**: ${{ needs.build.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Staging**: ${{ needs.deploy-staging.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Production**: ${{ needs.deploy-production.result }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Load Test**: ${{ needs.load-test.result }}" >> $GITHUB_STEP_SUMMARY
